// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blink-animation': string;
  'carret': string;
  'renderer': string;
  'rowsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
