// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documentCardContainer': string;
  'documentCardContainer__documentCard': string;
  'documentCardContainer__title': string;
  'documentCard__header': string;
  'documentCard__main': string;
  'main__margin': string;
  'main__rows': string;
}
export const cssExports: CssExports;
export default cssExports;
