// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'componentWrapper': string;
  'container': string;
  'currentLineHighlight': string;
  'editorBtn': string;
  'editorMargin': string;
  'editorView': string;
  'editorViewLines': string;
  'editorWrapper': string;
  'lineEnumeration': string;
  'menuDrawer': string;
  'textInput': string;
}
export const cssExports: CssExports;
export default cssExports;
