// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'fullWidth': string;
  'primary': string;
  'secondary': string;
}
export const cssExports: CssExports;
export default cssExports;
