// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closed': string;
  'drawerButton': string;
  'editorHeader': string;
  'renderMarkdownButton': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
