// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closed': string;
  'drawerButton': string;
  'markdownRendererHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
