// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documentViewer': string;
  'documentViewer__editorContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
