// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'documentListItem': string;
  'documentListItem__icon': string;
  'documentListItem__title': string;
}
export const cssExports: CssExports;
export default cssExports;
