// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'documentItems__cards': string;
  'documentItems__list': string;
  'documentViewer': string;
  'documentViewer__editorContainer': string;
  'documents__documentItems': string;
  'documents__header': string;
  'main__documents': string;
  'menu': string;
  'menu__main': string;
  'menu__sidebar': string;
  'showOption': string;
  'showOptionBtn': string;
  'sidebar__item': string;
  'sidebar__title': string;
}
export const cssExports: CssExports;
export default cssExports;
