// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'afterCurrent': string;
  'beforeCurrent': string;
  'closed': string;
  'items__item': string;
  'menuDrawer': string;
  'menuDrawer__items': string;
  'menuDrawer__menuButton': string;
}
export const cssExports: CssExports;
export default cssExports;
