// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'markdownContainer': string;
  'markdownContainer__editButtonContainer': string;
  'markdownContainer__main': string;
  'markdownContainer__markdownRenderer': string;
}
export const cssExports: CssExports;
export default cssExports;
