// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'documentItems__cards': string;
  'documentItems__list': string;
  'documents__documentItems': string;
  'documents__header': string;
  'linkGroup__link': string;
  'main__documents': string;
  'menu': string;
  'menu__main': string;
  'menu__navigation': string;
  'navigation__linkGroup': string;
  'navigation__title': string;
  'showOption': string;
  'showOptionBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
